// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/products": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog" | "/blog/:slug" | "/products" | "/about";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/blog/index.tsx": {
    id: "routes/blog/index";
    page: "/blog";
  };
  "routes/blog/$slug.tsx": {
    id: "routes/blog/$slug";
    page: "/blog/:slug";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/blog/index": typeof import("./app/routes/blog/index.tsx");
  "routes/blog/$slug": typeof import("./app/routes/blog/$slug.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
};