// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/personal": {
    params: {};
  };
  "/personal/:slug": {
    params: {
      "slug": string;
    };
  };
  "/tech": {
    params: {};
  };
  "/tech/:slug": {
    params: {
      "slug": string;
    };
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/personal" | "/personal/:slug" | "/tech" | "/tech/:slug" | "/about";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/personal/index.tsx": {
    id: "routes/personal/index";
    page: "/personal";
  };
  "routes/personal/$slug.tsx": {
    id: "routes/personal/$slug";
    page: "/personal/:slug";
  };
  "routes/tech/index.tsx": {
    id: "routes/tech/index";
    page: "/tech";
  };
  "routes/tech/$slug.tsx": {
    id: "routes/tech/$slug";
    page: "/tech/:slug";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/personal/index": typeof import("./app/routes/personal/index.tsx");
  "routes/personal/$slug": typeof import("./app/routes/personal/$slug.tsx");
  "routes/tech/index": typeof import("./app/routes/tech/index.tsx");
  "routes/tech/$slug": typeof import("./app/routes/tech/$slug.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
};